### ISSUE TITLE
 Fatal error: Call to undefined method TFactor::LoadAllBy() in \dolibarr\htdocs\factor\core\triggers\interface_99_modFactor_Factortrigger.class.php on line 155

### ISSUE THREAD

**Issue by guillaumecochard** [ATM-Consulting/dolibarr_module_factor#7]
Hi,

When I'm creating an invoice I have this error : 

 Fatal error: Call to undefined method TFactor::LoadAllBy() in \dolibarr\htdocs\factor\core\triggers\interface_99_modFactor_Factortrigger.class.php on line 155

Thanks !

**Comment by atm-gauthier** [comment]
Hello Guillaume,
Maybe your "abricot" module is not up to date.

**Comment by guillaumecochard** [comment]
Hi @atm-gauthier, which version of abricot module did you recommend ? 
Thanks !

**Comment by atm-gauthier** [comment]
Hi @guillaumecochard, LoadAllBy() function is available on abricot 2.0 version.
https://github.com/ATM-Consulting/dolibarr_module_abricot/tree/2.0

**Comment by guillaumecochard** [comment]
Perfect, thanks you !
